INSERT INTO CB_APPLICATION (ID, CODE, NAME) VALUES (1, 'CORE', 'CORE');

INSERT INTO CB_USER(ID,ACTIVE,EMAIL,EXPIRED,FIXED_NAME,LOCKED,NICK_NAME,PASSWORD,REGISTER_DATE,USERNAME,CREATOR_ID,CREATION_DATE)VALUES (1, TRUE, 'hadi.tayebi84@gmail.com', FALSE, 'haditayebi', FALSE, 'hadi', '202cb962ac59075b964b07152d234b70',current_date, 'admin', 1,current_date);

INSERT INTO CB_ROLE(ID, ACTIVE, CODE, DESCRIPTION, FIXED_NAME, NAME, VERSION, APPLICATION_ID,PARENT_ID,CREATOR_ID,CREATION_DATE)VALUES (1, TRUE, 'ROLE_ADMIN', 'system administrator', 'ROLE_ADMIN', 'ROLE_ADMIN', 0, 1,NULL, 1,current_date);
INSERT INTO CB_ROLE(ID, ACTIVE, CODE, DESCRIPTION, FIXED_NAME, NAME, VERSION, APPLICATION_ID,PARENT_ID,CREATOR_ID,CREATION_DATE)VALUES (2, TRUE, 'ROLE_USER', 'ROLE_USER', 'ROLE_USER', 'ROLE_USER', 0, 1,NULL, 1,current_date);
INSERT INTO CB_ROLE(ID, ACTIVE, CODE, DESCRIPTION, FIXED_NAME, NAME, VERSION, APPLICATION_ID,PARENT_ID,CREATOR_ID,CREATION_DATE)VALUES (3, TRUE, 'ROLE_EXPERT', 'ROLE_EXPERT', 'ROLE_EXPERT', 'ROLE_EXPERT', 0, 1,NULL, 1,current_date);

INSERT INTO CB_USER_ROLE(USER_ID, ROLE_ID)VALUES (1, 1);


DROP  FUNCTION TEST_FUNC;

CREATE FUNCTION TEST_FUNC(FIRSTNAME  VARCHAR(30),LASTNAME VARCHAR(30)) RETURNS  VARCHAR(60)
  BEGIN ATOMIC
    RETURN FIRSTNAME+LASTNAME;
  END

